version: 2.1
setup: true
orbs:
  # For the orb-tools-orb it must call itself within the first workflow,
  #   meaning this dev version will need to be published every 90 days.
  # No other orbs will need to import themselves here.
  orb-tools: circleci/orb-tools@11.1
  shellcheck: circleci/shellcheck@3.1

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters:
            tags:
              only: /.*/
      - orb-tools/pack:
          filters:
            tags:
              only: /.*/
      - orb-tools/review:
          filters:
            tags:
              only: /.*/
      - shellcheck/check:
          exclude: SC2148,SC2038,SC2086,SC2002,SC2016
          filters:
            tags:
              only: /.*/
      - orb-tools/publish:
          orb-name: scribe-security/scribe-tools
          vcs-type: << pipeline.project.type >>
          requires:
            [
              orb-tools/lint,
              orb-tools/review,
              orb-tools/pack,
              shellcheck/check,
            ]
          github-token: GHI_TOKEN
          context: orb-publishing
          filters:
            tags:
              only: /.*/
      - orb-tools/continue:
          pipeline-number: << pipeline.number >>
          vcs-type: << pipeline.project.type >>
          requires: [orb-tools/publish]
          filters:
            tags:
              only: /.*/
